// <auto-generated />
using System;
using MemorizarPalavraApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MemorizarPalavraApi.Migrations
{
    [DbContext(typeof(PalavraContext))]
    [Migration("20240528142358_CriacaoTabelaPalavra")]
    partial class CriacaoTabelaPalavra
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MemorizarPalavraApi.Entity.Palavra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aprendido")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DiaAtual")
                        .HasColumnType("datetime2");

                    b.Property<int>("NivelRevisao")
                        .HasColumnType("int");

                    b.Property<string>("PalavraLinguaEstrangeira")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PalavraTraduzida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProximaRevisao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Palavras");
                });
#pragma warning restore 612, 618
        }
    }
}
